'use client'

import { useEffect, useRef, useState } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'

interface Clone {
  id: string
  url: string
  title: string
  html: string
  created_at: string
}

interface SelectedElement {
  path: string
  tag: string
  text: string
  html: string
}

type Viewport = 'desktop' | 'mobile'

const LANGUAGES = [
  { code: 'nl', label: 'Dutch' },
  { code: 'en', label: 'English' },
  { code: 'de', label: 'German' },
  { code: 'fr', label: 'French' },
  { code: 'es', label: 'Spanish' },
  { code: 'it', label: 'Italian' },
  { code: 'pt', label: 'Portuguese' },
  { code: 'pl', label: 'Polish' },
  { code: 'ro', label: 'Romanian' },
  { code: 'sv', label: 'Swedish' },
]

function scopeHtmlForShopify(html: string, scopeClass: string): string {
  // Extract all <style> blocks
  const styles: string[] = []
  const htmlNoStyles = html.replace(/<style[^>]*>([\s\S]*?)<\/style>/gi, (_, css) => {
    styles.push(css)
    return ''
  })

  // Scope every CSS rule with the wrapper class
  const scopedCss = styles.map(css =>
    css.replace(/([^{}]+)\{/g, (match, selectors) => {
      const scoped = selectors
        .split(',')
        .map((s: string) => {
          const trimmed = s.trim()
          if (!trimmed || trimmed.startsWith('@') || trimmed.startsWith('from') || trimmed.startsWith('to') || /^\d/.test(trimmed)) return trimmed
          return trimmed
            .replace(/\bhtml\b/, `.${scopeClass}`)
            .replace(/\bbody\b/, `.${scopeClass}`)
            .replace(/^([^.#:\[])/, `.${scopeClass} $1`)
        })
        .join(', ')
      return `${scoped} {`
    })
  ).join('\n')

  // Extract <body> content
  const bodyMatch = htmlNoStyles.match(/<body[^>]*>([\s\S]*?)<\/body>/i)
  const bodyContent = bodyMatch ? bodyMatch[1] : htmlNoStyles

  return `{% comment %} Landing Page Clone — generated by Creative Hub {% endcomment %}
<div class="${scopeClass}">
  <style>
${scopedCss}
  </style>
  ${bodyContent}
</div>
`
}

export default function CloneEditor() {
  const { id } = useParams<{ id: string }>()
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const [clone, setClone] = useState<Clone | null>(null)
  const [loading, setLoading] = useState(true)
  const [selected, setSelected] = useState<SelectedElement | null>(null)
  const [editText, setEditText] = useState('')
  const [html, setHtml] = useState('')
  const [editMode, setEditMode] = useState(false)
  const [viewport, setViewport] = useState<Viewport>('desktop')
  const [translating, setTranslating] = useState(false)
  const [showLangMenu, setShowLangMenu] = useState(false)
  const langMenuRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    fetch(`/api/cloned-pages/${id}`)
      .then(r => r.json())
      .then(data => {
        setClone(data)
        setHtml(data.html)
        setLoading(false)
      })
  }, [id])

  useEffect(() => {
    function handleMessage(e: MessageEvent) {
      if (e.data?.type === 'ELEMENT_SELECTED') {
        setSelected(e.data)
        setEditText(e.data.text)
      }
    }
    window.addEventListener('message', handleMessage)
    return () => window.removeEventListener('message', handleMessage)
  }, [])

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (langMenuRef.current && !langMenuRef.current.contains(e.target as Node)) {
        setShowLangMenu(false)
      }
    }
    document.addEventListener('mousedown', handleClick)
    return () => document.removeEventListener('mousedown', handleClick)
  }, [])

  function injectEditScript(rawHtml: string, editModeOn: boolean): string {
    const script = editModeOn ? `
<script>
(function() {
  var selected = null;
  document.addEventListener('click', function(e) {
    e.preventDefault();
    e.stopPropagation();
    if (selected) selected.style.outline = '';
    selected = e.target;
    selected.style.outline = '2px solid #e8c547';
    selected.style.outlineOffset = '2px';
    var path = [];
    var el = selected;
    while (el && el !== document.body) {
      var idx = Array.from(el.parentNode ? el.parentNode.children : []).indexOf(el);
      path.unshift(el.tagName.toLowerCase() + ':nth-child(' + (idx + 1) + ')');
      el = el.parentElement;
    }
    window.parent.postMessage({
      type: 'ELEMENT_SELECTED',
      tag: selected.tagName,
      text: selected.innerText || selected.textContent || '',
      html: selected.innerHTML || '',
      path: path.join(' > ')
    }, '*');
  }, true);
  window.addEventListener('message', function(e) {
    if (e.data && e.data.type === 'UPDATE_ELEMENT' && selected) {
      selected.textContent = e.data.text;
    }
  });
})();
<\/script>` : ''

    if (rawHtml.includes('</body>')) {
      return rawHtml.replace('</body>', script + '</body>')
    }
    return rawHtml + script
  }

  function applyEdit() {
    if (!selected || !iframeRef.current?.contentWindow) return
    iframeRef.current.contentWindow.postMessage({ type: 'UPDATE_ELEMENT', text: editText }, '*')
    setSelected(prev => prev ? { ...prev, text: editText } : null)
  }

  function downloadHtml() {
    if (!html) return
    const blob = new Blob([html], { type: 'text/html' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${clone?.title || 'clone'}.html`
    a.click()
  }

  function downloadShopify() {
    if (!html) return
    const scopeClass = `lp-clone-${id.slice(0, 8)}`
    const liquid = scopeHtmlForShopify(html, scopeClass)
    const blob = new Blob([liquid], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${(clone?.title || 'clone').toLowerCase().replace(/\s+/g, '-')}.liquid`
    a.click()
  }

  async function translate(langCode: string, langLabel: string) {
    setShowLangMenu(false)
    setTranslating(true)
    setSelected(null)
    try {
      const res = await fetch('/api/translate-page', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id, language: langLabel }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Translation failed')
      setHtml(data.html)
    } catch (err: any) {
      alert(err.message)
    } finally {
      setTranslating(false)
    }
  }

  if (loading) {
    return (
      <>
        <div className="topbar"><div className="topbar-title">Loading…</div></div>
        <div className="content" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 300 }}>
          <span className="spinner" />
        </div>
      </>
    )
  }

  if (!clone) {
    return (
      <>
        <div className="topbar"><div className="topbar-title">Not found</div></div>
        <div className="content"><Link href="/landing-page" className="btn">← Back</Link></div>
      </>
    )
  }

  const iframeSrc = injectEditScript(html, editMode)

  return (
    <>
      <div className="topbar">
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <Link href="/landing-page" className="btn btn-sm">← Back</Link>
          <div className="topbar-title" style={{ fontSize: 15 }}>{clone.title || 'Untitled Page'}</div>
        </div>
        <div className="topbar-actions">

          {/* Viewport toggle */}
          <div className="viewport-toggle">
            <button
              className={`viewport-btn${viewport === 'desktop' ? ' active' : ''}`}
              onClick={() => setViewport('desktop')}
              title="Desktop view"
            >
              🖥
            </button>
            <button
              className={`viewport-btn${viewport === 'mobile' ? ' active' : ''}`}
              onClick={() => setViewport('mobile')}
              title="Mobile view (390px)"
            >
              📱
            </button>
          </div>

          {/* Edit mode */}
          <button
            className={`btn btn-sm${editMode ? ' btn-accent' : ''}`}
            onClick={() => { setEditMode(!editMode); setSelected(null) }}
          >
            {editMode ? '✓ Editing' : '✎ Edit'}
          </button>

          {/* Translate */}
          <div style={{ position: 'relative' }} ref={langMenuRef}>
            <button
              className="btn btn-sm"
              onClick={() => setShowLangMenu(p => !p)}
              disabled={translating}
            >
              {translating ? <><span className="spinner" /> Translating…</> : '🌐 Translate'}
            </button>
            {showLangMenu && (
              <div className="lang-menu">
                {LANGUAGES.map(lang => (
                  <button
                    key={lang.code}
                    className="lang-menu-item"
                    onClick={() => translate(lang.code, lang.label)}
                  >
                    {lang.label}
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Download */}
          <div style={{ position: 'relative' }} className="download-group">
            <button className="btn btn-sm" onClick={downloadHtml}>↓ HTML</button>
            <button className="btn btn-sm btn-accent" onClick={downloadShopify} title="Scoped .liquid section — works with every Shopify theme">
              ↓ Shopify
            </button>
          </div>

        </div>
      </div>

      <div className="clone-editor">
        <div className="clone-preview-pane">
          <div className="clone-preview-toolbar">
            <div className="clone-preview-url">{clone.url}</div>
            <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexShrink: 0 }}>
              {viewport === 'mobile' && (
                <span style={{ fontSize: 11, color: 'var(--text3)', fontFamily: 'DM Mono' }}>390px</span>
              )}
              {editMode && (
                <span style={{ fontSize: 11, color: 'var(--accent)', fontFamily: 'DM Mono' }}>
                  click to edit
                </span>
              )}
            </div>
          </div>
          <div className="clone-iframe-wrap" style={{ background: viewport === 'mobile' ? 'var(--bg)' : undefined }}>
            <div className={`clone-iframe-inner${viewport === 'mobile' ? ' mobile' : ''}`}>
              <iframe
                ref={iframeRef}
                key={`${editMode ? 'edit' : 'view'}-${viewport}`}
                srcDoc={iframeSrc}
                sandbox="allow-scripts allow-same-origin"
                title="Page preview"
              />
            </div>
          </div>
        </div>

        <div className="clone-edit-pane">
          <div className="clone-edit-header">
            <div className="clone-edit-title">Element Editor</div>
            <div className="clone-edit-hint">
              {editMode
                ? 'Click any element in the preview to select and edit it.'
                : 'Enable Edit Mode to select and modify page elements.'}
            </div>
          </div>

          {!editMode ? (
            <div className="clone-edit-empty">
              <span style={{ fontSize: 32, opacity: 0.2 }}>✎</span>
              Enable Edit Mode to<br />interact with the page.
            </div>
          ) : !selected ? (
            <div className="clone-edit-empty">
              <span style={{ fontSize: 32, opacity: 0.2 }}>◎</span>
              Click any element<br />in the preview to edit it.
            </div>
          ) : (
            <div className="clone-edit-selection">
              <div><span className="clone-edit-tag">{selected.tag}</span></div>
              <div className="clone-edit-field">
                <label className="field-label">Text content</label>
                <textarea
                  value={editText}
                  onChange={e => setEditText(e.target.value)}
                  rows={5}
                />
              </div>
              <button className="btn btn-accent" onClick={applyEdit}>Apply Change</button>
              <div className="notice-box">
                Changes are live in the preview. Download HTML or Shopify to save.
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  )
}
