'use client'

import { useEffect, useRef, useState, useMemo } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import ConfirmModal from '@/components/ConfirmModal'

interface Clone {
  id: string
  url: string
  title: string
  html: string
  created_at: string
}

interface SelectedElement {
  path: string
  tag: string
  text: string
  html: string
  src?: string | null
  alt?: string | null
}

interface Section {
  id: string
  tag: string
  label: string
  rawHtml: string
}

type Viewport = 'desktop' | 'mobile'
type PendingAction =
  | { action: 'download' | 'copy'; id: string }
  | { action: 'ai'; id: string; resolve: (html: string) => void }

const LANGUAGES = [
  { code: 'nl', label: 'Dutch' },
  { code: 'en', label: 'English' },
  { code: 'de', label: 'German' },
  { code: 'fr', label: 'French' },
  { code: 'es', label: 'Spanish' },
  { code: 'it', label: 'Italian' },
  { code: 'pt', label: 'Portuguese' },
  { code: 'pl', label: 'Polish' },
  { code: 'ro', label: 'Romanian' },
  { code: 'sv', label: 'Swedish' },
]

function scopeHtmlForShopify(html: string, scopeClass: string): string {
  const styles: string[] = []
  const htmlNoStyles = html.replace(/<style[^>]*>([\s\S]*?)<\/style>/gi, (_, css) => {
    styles.push(css); return ''
  })
  const scopedCss = styles.map(css =>
    css.replace(/([^{}]+)\{/g, (match, selectors) => {
      const scoped = selectors.split(',').map((s: string) => {
        const t = s.trim()
        if (!t || t.startsWith('@') || t.startsWith('from') || t.startsWith('to') || /^\d/.test(t)) return t
        return t.replace(/\bhtml\b/, `.${scopeClass}`).replace(/\bbody\b/, `.${scopeClass}`).replace(/^([^.#:\[])/, `.${scopeClass} $1`)
      }).join(', ')
      return `${scoped} {`
    })
  ).join('\n')
  const bodyMatch = htmlNoStyles.match(/<body[^>]*>([\s\S]*?)<\/body>/i)
  return `{% comment %} Generated by Creative Hub {% endcomment %}\n<div class="${scopeClass}">\n  <style>\n${scopedCss}\n  </style>\n  ${bodyMatch ? bodyMatch[1] : htmlNoStyles}\n</div>\n`
}

// ── Section card component ──────────────────────────────────────────────────

interface SectionCardProps {
  section: Section
  pageStyles: string
  viewport: Viewport
  selected: boolean
  aiGenerating: boolean
  aiTargetId: string | null
  copyFeedback: string | null
  onCleanHtml: (s: Section) => void
  onCopyRaw: (id: string) => void
  onDownload: (id: string) => void
  onDelete: (s: Section) => void
  onSelect: (s: Section) => void
}

function SectionCard({
  section, pageStyles, viewport, selected,
  aiGenerating, aiTargetId, copyFeedback,
  onCleanHtml, onCopyRaw, onDownload, onDelete, onSelect,
}: SectionCardProps) {
  const [iframeH, setIframeH] = useState(300)
  const [scale, setScale] = useState(0.6)
  const wrapRef = useRef<HTMLDivElement>(null)
  const srcWidth = viewport === 'mobile' ? 390 : 1280

  useEffect(() => {
    if (!wrapRef.current) return
    const obs = new ResizeObserver(entries => {
      const w = entries[0].contentRect.width
      if (w > 0) setScale(w / srcWidth)
    })
    obs.observe(wrapRef.current)
    return () => obs.disconnect()
  }, [srcWidth])

  const doc = useMemo(() => {
    if (!section.rawHtml) return ''
    return `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}html,body{margin:0;padding:0}</style><style>${pageStyles}</style></head><body>${section.rawHtml}</body></html>`
  }, [section.rawHtml, pageStyles])

  const containerH = section.rawHtml ? Math.ceil(iframeH * scale) : 100

  return (
    <div className={`section-card${selected ? ' selected' : ''}`} id={`sec-card-${section.id}`}>
      <div className="section-card-header">
        <span className="section-card-tag">{section.tag}</span>
        <span className="section-card-label">{section.label}</span>
        <div className="section-card-actions">
          <button
            className="btn btn-sm section-card-ai-btn"
            title="Generate Shopify Liquid section with editable schema"
            disabled={aiGenerating}
            onClick={e => { e.stopPropagation(); onCleanHtml(section) }}
          >
            {aiGenerating && aiTargetId === section.id ? '…' : '✦ Liquid'}
          </button>
          <button className="btn btn-sm" title="Copy raw HTML" onClick={e => { e.stopPropagation(); onCopyRaw(section.id) }}>
            {copyFeedback === section.id ? '✓' : '⎘'}
          </button>
          <button className="btn btn-sm" title="Download HTML" onClick={e => { e.stopPropagation(); onDownload(section.id) }}>↓</button>
          <button className="btn btn-sm" title="Delete section" style={{ color: 'var(--red)' }} onClick={e => { e.stopPropagation(); onDelete(section) }}>🗑</button>
        </div>
      </div>
      <div
        ref={wrapRef}
        className={`section-card-preview${selected ? ' active' : ''}`}
        style={{ height: containerH }}
        onClick={() => onSelect(section)}
      >
        {!section.rawHtml ? (
          <div className="section-card-skeleton" />
        ) : (
          <iframe
            srcDoc={doc}
            sandbox="allow-same-origin"
            title={section.label}
            onLoad={e => {
              try {
                const body = (e.target as HTMLIFrameElement).contentDocument?.body
                if (body) setIframeH(Math.max(80, body.scrollHeight))
              } catch { /* cross-origin */ }
            }}
            style={{
              width: srcWidth,
              height: iframeH,
              border: 'none',
              display: 'block',
              transform: `scale(${scale})`,
              transformOrigin: '0 0',
              pointerEvents: 'none',
            }}
          />
        )}
      </div>
    </div>
  )
}

// ── Main editor component ───────────────────────────────────────────────────

export default function CloneEditor() {
  const { id } = useParams<{ id: string }>()
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const [clone, setClone] = useState<Clone | null>(null)
  const [loading, setLoading] = useState(true)
  const [selected, setSelected] = useState<SelectedElement | null>(null)
  const [editText, setEditText] = useState('')
  const [editSrc, setEditSrc] = useState('')
  const [html, setHtml] = useState('')
  const [editMode, setEditMode] = useState(false)
  const [viewport, setViewport] = useState<Viewport>('desktop')
  const [translating, setTranslating] = useState(false)
  const [translateProgress, setTranslateProgress] = useState(0)
  const [showLangMenu, setShowLangMenu] = useState(false)
  const [sections, setSections] = useState<Section[]>([])
  const [selectedSectionId, setSelectedSectionId] = useState<string | null>(null)
  const [sectionCodeHtml, setSectionCodeHtml] = useState<string>('')
  const [sectionCodeLabel, setSectionCodeLabel] = useState('')
  const [sectionCodeIsClean, setSectionCodeIsClean] = useState(false)
  const [sectionCodeCleanId, setSectionCodeCleanId] = useState<string | null>(null)
  const [codeCopied, setCodeCopied] = useState(false)
  const [isDirty, setIsDirty] = useState(false)
  const [saving, setSaving] = useState(false)
  const [deleteSection, setDeleteSection] = useState<Section | null>(null)
  const [aiGenerating, setAiGenerating] = useState(false)
  const [copyFeedback, setCopyFeedback] = useState<string | null>(null)

  // Shopify connection state
  const [shopifyConn, setShopifyConn] = useState<{ storeUrl: string; themeId: string | null; themeName: string | null } | null>(null)
  const [shopifyModal, setShopifyModal] = useState(false)
  const [shopifyStep, setShopifyStep] = useState<'credentials' | 'theme'>('credentials')
  const [shopifyForm, setShopifyForm] = useState({ storeUrl: '', token: '' })
  const [shopifyThemes, setShopifyThemes] = useState<{ id: string; name: string; role: string }[]>([])
  const [shopifySelectedTheme, setShopifySelectedTheme] = useState('')
  const [shopifyConnecting, setShopifyConnecting] = useState(false)
  const [shopifyError, setShopifyError] = useState('')
  const [shopifyPushing, setShopifyPushing] = useState(false)
  const [shopifyPushResult, setShopifyPushResult] = useState<{ ok?: boolean; error?: string; editorUrl?: string; filename?: string } | null>(null)

  const langMenuRef = useRef<HTMLDivElement>(null)
  const shopifyDropdownRef = useRef<HTMLDivElement>(null)
  const htmlRef = useRef(html)
  const sectionsRef = useRef(sections)
  const pendingAction = useRef<PendingAction | null>(null)
  const fullHtmlResolve = useRef<((h: string) => void) | null>(null)
  const savedHtmlRef = useRef('')
  const viewResolve = useRef<((h: string) => void) | null>(null)

  useEffect(() => { htmlRef.current = html }, [html])
  useEffect(() => { sectionsRef.current = sections }, [sections])

  // Derive page styles for section card previews
  const pageStyles = useMemo(() =>
    (html.match(/<style[^>]*>([\s\S]*?)<\/style>/gi) ?? [])
      .map(s => s.replace(/<\/?style[^>]*>/gi, ''))
      .join('\n'),
    [html]
  )

  useEffect(() => {
    fetch(`/api/cloned-pages/${id}`)
      .then(r => r.json())
      .then(data => {
        setClone(data)
        setHtml(data.html)
        savedHtmlRef.current = data.html
        setLoading(false)
      })
  }, [id])

  useEffect(() => {
    fetch('/api/shopify/connection')
      .then(r => r.json())
      .then(data => {
        if (data.connected) setShopifyConn({ storeUrl: data.storeUrl, themeId: data.themeId, themeName: data.themeName })
      })
      .catch(() => {})
  }, [])

  useEffect(() => {
    function handleMessage(e: MessageEvent) {
      if (e.data?.type === 'SECTIONS_LOADED') {
        const incoming: Section[] = e.data.sections.map((s: any) => ({
          ...s,
          rawHtml: sectionsRef.current.find(p => p.id === s.id)?.rawHtml ?? '',
        }))
        setSections(incoming)
        // Batch-fetch all section HTML from the hidden iframe
        setTimeout(() => {
          iframeRef.current?.contentWindow?.postMessage({ type: 'GET_ALL_SECTIONS_HTML' }, '*')
        }, 150)
      } else if (e.data?.type === 'ALL_SECTIONS_HTML') {
        const map: Record<string, string> = {}
        e.data.sections.forEach((s: any) => { map[s.id] = s.outerHtml })
        setSections(prev => prev.map(s => ({ ...s, rawHtml: map[s.id] ?? s.rawHtml })))
      } else if (e.data?.type === 'ELEMENT_SELECTED') {
        setSelected(e.data)
        setEditText(e.data.tag === 'IMG' ? (e.data.alt ?? '') : (e.data.text ?? ''))
        setEditSrc(e.data.src ?? '')
      } else if (e.data?.type === 'EDIT_APPLIED') {
        setIsDirty(true)
        // Refresh section HTML after DOM change
        setTimeout(() => {
          iframeRef.current?.contentWindow?.postMessage({ type: 'GET_ALL_SECTIONS_HTML' }, '*')
        }, 100)
      } else if (e.data?.type === 'FULL_HTML') {
        if (fullHtmlResolve.current) { fullHtmlResolve.current(e.data.html); fullHtmlResolve.current = null }
      } else if (e.data?.type === 'SECTION_VIEW') {
        if (viewResolve.current) { viewResolve.current(e.data.outerHtml); viewResolve.current = null }
      } else if (e.data?.type === 'SECTION_HTML') {
        const pa = pendingAction.current
        if (!pa || pa.id !== e.data.id) return
        pendingAction.current = null
        if (pa.action === 'ai') {
          pa.resolve(e.data.outerHtml)
        } else if (pa.action === 'copy') {
          navigator.clipboard.writeText(e.data.outerHtml).catch(() => {})
          setCopyFeedback(e.data.id)
          setTimeout(() => setCopyFeedback(null), 1500)
        } else {
          const styleMatches = htmlRef.current.match(/<style[^>]*>[\s\S]*?<\/style>/gi) ?? []
          const fullDoc = `<!DOCTYPE html>\n<html>\n<head>\n<meta charset="utf-8">\n${styleMatches.join('\n')}\n</head>\n<body>\n${e.data.outerHtml}\n</body>\n</html>`
          const section = sectionsRef.current.find(s => s.id === e.data.id)
          const blob = new Blob([fullDoc], { type: 'text/html' })
          const a = document.createElement('a')
          a.href = URL.createObjectURL(blob)
          a.download = `${(section?.label || e.data.id).toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40)}.html`
          a.click()
        }
      }
    }
    window.addEventListener('message', handleMessage)
    return () => window.removeEventListener('message', handleMessage)
  }, [])

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (langMenuRef.current && !langMenuRef.current.contains(e.target as Node)) setShowLangMenu(false)
      if (shopifyDropdownRef.current && !shopifyDropdownRef.current.contains(e.target as Node)) setShopifyModal(false)
    }
    document.addEventListener('mousedown', handleClick)
    return () => document.removeEventListener('mousedown', handleClick)
  }, [])

  function buildIframeSrc(rawHtml: string, editModeOn: boolean): string {
    const script = `
<script data-lp-injected="1">
(function() {
  var selectedEl = null;
  var activeSec = null;
  var secCounter = 0;

  var SKIP_TAGS = ['STYLE','SCRIPT','LINK','META','NOSCRIPT','HEAD'];

  function getSectionLabel(el) {
    var ariaLabel = el.getAttribute('aria-label');
    if (ariaLabel && ariaLabel.trim().length > 1) return ariaLabel.trim().slice(0, 70);
    var elId = el.id;
    if (elId && elId.length > 2 && elId.length < 50 && !/^\\d+$/.test(elId)) {
      return elId.replace(/[-_]/g, ' ').trim();
    }
    var h = el.querySelector('h1,h2,h3,h4,h5,h6');
    if (h) { var ht = h.textContent.trim(); if (ht.length > 1) return ht.slice(0, 70); }
    var strong = el.querySelector('strong, b');
    if (strong) { var st = strong.textContent.trim(); if (st.length > 2 && st.length < 80) return st.slice(0, 70); }
    var btn = el.querySelector('button, [class*="btn-"], [class*="-btn"], [class*="cta"]');
    if (btn) { var bt = btn.textContent.trim(); if (bt.length > 1 && bt.length < 50) return bt.slice(0, 50); }
    var p = el.querySelector('p');
    if (p) { var pt = p.textContent.trim(); if (pt.length > 3) return pt.slice(0, 70); }
    var text = el.textContent.trim();
    if (text.length > 1) return text.slice(0, 70);
    return el.tagName.toLowerCase();
  }

  function findSectionElements() {
    var candidates = [];
    var mainEl = document.querySelector('main, [role="main"]');
    if (mainEl) {
      candidates = Array.from(mainEl.children).filter(function(el) {
        return SKIP_TAGS.indexOf(el.tagName) === -1 && (el.textContent || '').trim().length > 20;
      });
      if (candidates.length <= 2 && candidates.length > 0) {
        var expanded = [];
        candidates.forEach(function(el) {
          var sub = Array.from(el.children).filter(function(c) {
            return SKIP_TAGS.indexOf(c.tagName) === -1 && (c.textContent || '').trim().length > 20;
          });
          if (sub.length >= 2) { sub.forEach(function(s) { expanded.push(s); }); }
          else { expanded.push(el); }
        });
        if (expanded.length > candidates.length) candidates = expanded;
      }
    }
    if (candidates.length < 2) {
      candidates = Array.from(document.body.children).filter(function(el) {
        return SKIP_TAGS.indexOf(el.tagName) === -1 && (el.textContent || '').trim().length > 20;
      });
    }
    return candidates;
  }

  function scanSections() {
    var elements = findSectionElements();
    var result = [];
    elements.forEach(function(el) {
      var secId = el.getAttribute('data-lp-sec');
      if (!secId) { secId = 'sec-' + (++secCounter); el.setAttribute('data-lp-sec', secId); }
      result.push({ id: secId, tag: el.tagName.toLowerCase(), label: getSectionLabel(el) });
    });
    window.parent.postMessage({ type: 'SECTIONS_LOADED', sections: result }, '*');
  }

  function getSecEl(id) { return document.querySelector('[data-lp-sec="' + id + '"]'); }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', scanSections);
  } else {
    scanSections();
  }

  window.addEventListener('message', function(e) {
    if (!e.data) return;

    if (e.data.type === 'GET_ALL_SECTIONS_HTML') {
      var result = [];
      document.querySelectorAll('[data-lp-sec]').forEach(function(el) {
        result.push({ id: el.getAttribute('data-lp-sec'), outerHtml: el.outerHTML });
      });
      window.parent.postMessage({ type: 'ALL_SECTIONS_HTML', sections: result }, '*');
    }

    if (e.data.type === 'HIGHLIGHT_SECTION') {
      if (activeSec) { activeSec.style.outline = ''; activeSec.style.outlineOffset = ''; }
      activeSec = getSecEl(e.data.id);
      if (activeSec) {
        activeSec.style.outline = '2px solid #e8c547';
        activeSec.style.outlineOffset = '4px';
      }
    }

    if (e.data.type === 'CLEAR_SECTION') {
      if (activeSec) { activeSec.style.outline = ''; activeSec.style.outlineOffset = ''; activeSec = null; }
    }

    if (e.data.type === 'DELETE_SECTION') {
      var el = getSecEl(e.data.id);
      if (el) { el.remove(); scanSections(); window.parent.postMessage({ type: 'EDIT_APPLIED' }, '*'); }
    }

    if (e.data.type === 'REPLACE_SECTION') {
      var el = getSecEl(e.data.id);
      if (el && e.data.html) {
        el.outerHTML = e.data.html;
        scanSections();
        window.parent.postMessage({ type: 'EDIT_APPLIED' }, '*');
      }
    }

    if (e.data.type === 'GET_SECTION_HTML') {
      var el = getSecEl(e.data.id);
      if (el) window.parent.postMessage({ type: 'SECTION_HTML', id: e.data.id, outerHtml: el.outerHTML }, '*');
    }

    if (e.data.type === 'GET_SECTION_VIEW') {
      var el = getSecEl(e.data.id);
      if (el) window.parent.postMessage({ type: 'SECTION_VIEW', id: e.data.id, outerHtml: el.outerHTML }, '*');
    }

    if (e.data.type === 'GET_FULL_HTML') {
      var clone = document.documentElement.cloneNode(true);
      Array.from(clone.querySelectorAll('[data-lp-sec]')).forEach(function(el) { el.removeAttribute('data-lp-sec'); });
      Array.from(clone.querySelectorAll('script[data-lp-injected]')).forEach(function(s) { s.remove(); });
      window.parent.postMessage({ type: 'FULL_HTML', html: '<!DOCTYPE html>' + clone.outerHTML }, '*');
    }

    if (e.data.type === 'UPDATE_ELEMENT' && selectedEl) {
      selectedEl.innerHTML = e.data.html;
      window.parent.postMessage({ type: 'EDIT_APPLIED' }, '*');
    }

    if (e.data.type === 'UPDATE_IMAGE' && selectedEl) {
      if (e.data.src) selectedEl.src = e.data.src;
      if (typeof e.data.alt === 'string') selectedEl.alt = e.data.alt;
      window.parent.postMessage({ type: 'EDIT_APPLIED' }, '*');
    }
  });

  ${editModeOn ? `
  document.addEventListener('click', function(e) {
    e.preventDefault();
    e.stopPropagation();
    if (selectedEl) selectedEl.style.outline = '';
    selectedEl = e.target;
    selectedEl.style.outline = '2px solid #e8c547';
    selectedEl.style.outlineOffset = '2px';
    var path = [];
    var el = selectedEl;
    while (el && el !== document.body) {
      var idx = Array.from(el.parentNode ? el.parentNode.children : []).indexOf(el);
      path.unshift(el.tagName.toLowerCase() + ':nth-child(' + (idx + 1) + ')');
      el = el.parentElement;
    }
    var isImg = selectedEl.tagName === 'IMG';
    window.parent.postMessage({
      type: 'ELEMENT_SELECTED',
      tag: selectedEl.tagName,
      text: selectedEl.innerHTML || '',
      html: selectedEl.innerHTML || '',
      path: path.join(' > '),
      src: isImg ? selectedEl.src : null,
      alt: isImg ? (selectedEl.alt || '') : null,
    }, '*');
  }, true);
  ` : ''}
})();
<\/script>`
    if (rawHtml.includes('</body>')) return rawHtml.replace('</body>', script + '</body>')
    return rawHtml + script
  }

  function requestSectionHtml(id: string, action: 'download' | 'copy') {
    pendingAction.current = { action, id }
    iframeRef.current?.contentWindow?.postMessage({ type: 'GET_SECTION_HTML', id }, '*')
  }

  async function generateCleanHtml(section: Section) {
    setAiGenerating(true)
    setSelectedSectionId(section.id)
    setSectionCodeLabel(section.label)
    setSectionCodeHtml('loading')
    setSectionCodeIsClean(false)
    setSectionCodeCleanId(null)

    const sectionHtml = await new Promise<string>(resolve => {
      pendingAction.current = { action: 'ai', id: section.id, resolve }
      iframeRef.current?.contentWindow?.postMessage({ type: 'GET_SECTION_HTML', id: section.id }, '*')
      setTimeout(() => { if (pendingAction.current?.action === 'ai') { pendingAction.current = null; resolve('') } }, 5000)
    })
    const currentHtml = savedHtmlRef.current || htmlRef.current
    const pageStylesStr = (currentHtml.match(/<style[^>]*>([\s\S]*?)<\/style>/gi) ?? []).map(s => s.replace(/<\/?style[^>]*>/gi, '')).join('\n')
    try {
      const res = await fetch('/api/clean-section', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ sectionHtml, pageStyles: pageStylesStr, pageUrl: clone?.url }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Generation failed')
      setSectionCodeHtml(data.html)
      setSectionCodeIsClean(true)
      setSectionCodeCleanId(section.id)
    } catch (err: any) {
      setSectionCodeHtml(`/* Error: ${err.message} */`)
    } finally {
      setAiGenerating(false)
    }
  }

  function applyAiToPage() {
    if (!sectionCodeIsClean || !sectionCodeCleanId || !sectionCodeHtml || sectionCodeHtml === 'loading') return
    iframeRef.current?.contentWindow?.postMessage({ type: 'REPLACE_SECTION', id: sectionCodeCleanId, html: sectionCodeHtml }, '*')
    setSectionCodeIsClean(false)
    setSectionCodeCleanId(null)
  }

  async function applyEdit() {
    if (!selected || !iframeRef.current?.contentWindow) return
    if (selected.tag === 'IMG') {
      iframeRef.current.contentWindow.postMessage({ type: 'UPDATE_IMAGE', src: editSrc, alt: editText }, '*')
      setSelected(prev => prev ? { ...prev, src: editSrc, alt: editText } : null)
    } else {
      iframeRef.current.contentWindow.postMessage({ type: 'UPDATE_ELEMENT', html: editText }, '*')
      setSelected(prev => prev ? { ...prev, text: editText, html: editText } : null)
    }
    await new Promise(r => setTimeout(r, 80))
    await saveToDb(true)
  }

  async function saveToDb(auto = false) {
    if (!auto) setSaving(true)
    const liveHtml = await new Promise<string>(resolve => {
      fullHtmlResolve.current = resolve
      iframeRef.current?.contentWindow?.postMessage({ type: 'GET_FULL_HTML' }, '*')
      setTimeout(() => resolve(htmlRef.current), 4000)
    })
    try {
      await fetch(`/api/cloned-pages/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ html: liveHtml }),
      })
      savedHtmlRef.current = liveHtml
      setHtml(liveHtml)
      setIsDirty(false)
    } catch {
      if (!auto) alert('Save failed. Please try again.')
    } finally {
      if (!auto) setSaving(false)
    }
  }

  async function downloadHtml() {
    const content = savedHtmlRef.current || htmlRef.current
    if (!content) return
    const blob = new Blob([content], { type: 'text/html' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${clone?.title || 'clone'}.html`
    a.click()
  }

  function downloadShopify() {
    const content = savedHtmlRef.current || html
    if (!content) return
    const scopeClass = `lp-clone-${id.slice(0, 8)}`
    const liquid = scopeHtmlForShopify(content, scopeClass)
    const blob = new Blob([liquid], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${(clone?.title || 'clone').toLowerCase().replace(/\s+/g, '-')}.liquid`
    a.click()
  }

  function doDeleteSection() {
    if (!deleteSection) return
    iframeRef.current?.contentWindow?.postMessage({ type: 'DELETE_SECTION', id: deleteSection.id }, '*')
    setSections(prev => prev.filter(s => s.id !== deleteSection.id))
    if (selectedSectionId === deleteSection.id) {
      setSelectedSectionId(null)
      setSectionCodeHtml('')
    }
    setDeleteSection(null)
    setIsDirty(true)
  }

  async function translate(langCode: string, langLabel: string) {
    setShowLangMenu(false)
    setTranslating(true)
    setTranslateProgress(0)
    setSelected(null)
    try {
      const res = await fetch('/api/translate-page', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id, language: langLabel }),
      })
      if (!res.ok || !res.body) throw new Error((await res.json()).error || 'Translation failed')
      const reader = res.body.getReader()
      const decoder = new TextDecoder()
      let buffer = ''
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        buffer += decoder.decode(value, { stream: true })
        const parts = buffer.split('\n\n')
        buffer = parts.pop() ?? ''
        for (const part of parts) {
          if (!part.startsWith('data: ')) continue
          const event = JSON.parse(part.slice(6))
          if (event.type === 'progress') setTranslateProgress(event.value)
          else if (event.type === 'done') {
            setTranslateProgress(1)
            setHtml(event.html)
            savedHtmlRef.current = event.html
            setIsDirty(false)
          }
          else if (event.type === 'error') throw new Error(event.error)
        }
      }
    } catch (err: any) {
      alert(err.message)
    } finally {
      setTimeout(() => { setTranslating(false); setTranslateProgress(0) }, 600)
    }
  }

  async function connectShopify() {
    setShopifyConnecting(true)
    setShopifyError('')
    try {
      const res = await fetch('/api/shopify/connection', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ storeUrl: shopifyForm.storeUrl, accessToken: shopifyForm.token }),
      })
      const data = await res.json()
      if (!res.ok) { setShopifyError(data.error || 'Connection failed'); return }
      setShopifyThemes(data.themes ?? [])
      setShopifySelectedTheme(data.themes?.find((t: any) => t.role === 'main')?.id ?? data.themes?.[0]?.id ?? '')
      setShopifyStep('theme')
    } catch {
      setShopifyError('Network error — please try again.')
    } finally {
      setShopifyConnecting(false)
    }
  }

  async function saveShopifyTheme() {
    const theme = shopifyThemes.find(t => t.id === shopifySelectedTheme)
    if (!theme) return
    await fetch('/api/shopify/connection', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ themeId: theme.id, themeName: theme.name }),
    })
    setShopifyConn({ storeUrl: shopifyForm.storeUrl.replace(/^https?:\/\//, '').replace(/\/$/, ''), themeId: theme.id, themeName: theme.name })
    setShopifyModal(false)
    setShopifyStep('credentials')
    setShopifyForm({ storeUrl: '', token: '' })
    setShopifyThemes([])
  }

  async function pushToShopify() {
    if (!sectionCodeHtml || sectionCodeHtml === 'loading' || !sectionCodeIsClean) return
    if (!shopifyConn?.themeId) { setShopifyModal(true); return }
    setShopifyPushing(true)
    setShopifyPushResult(null)
    try {
      const res = await fetch('/api/shopify/push-section', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ liquidContent: sectionCodeHtml, sectionName: sectionCodeLabel }),
      })
      const data = await res.json()
      setShopifyPushResult(res.ok ? { ok: true, editorUrl: data.editorUrl, filename: data.filename } : { error: data.error })
    } catch {
      setShopifyPushResult({ error: 'Network error' })
    } finally {
      setShopifyPushing(false)
    }
  }

  if (loading) return (
    <>
      <div className="topbar"><div className="topbar-title">Loading…</div></div>
      <div className="content" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 300 }}>
        <span className="spinner" />
      </div>
    </>
  )

  if (!clone) return (
    <>
      <div className="topbar"><div className="topbar-title">Not found</div></div>
      <div className="content"><Link href="/landing-page" className="btn">← Back</Link></div>
    </>
  )

  const iframeSrc = buildIframeSrc(html, editMode)

  return (
    <>
      {/* ── Topbar ── */}
      <div className="topbar" style={{ position: 'relative' }}>
        {translating && <div className="translate-progress-bar" style={{ width: `${Math.round(translateProgress * 100)}%` }} />}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <Link href="/landing-page" className="btn btn-sm">← Back</Link>
          <div className="topbar-title" style={{ fontSize: 15 }}>{clone.title || 'Untitled Page'}</div>
          {isDirty && <span className="unsaved-dot" title="Unsaved changes" />}
        </div>
        <div className="topbar-actions">
          <div className="viewport-toggle">
            <button className={`viewport-btn${viewport === 'desktop' ? ' active' : ''}`} onClick={() => setViewport('desktop')} title="Desktop">🖥</button>
            <button className={`viewport-btn${viewport === 'mobile' ? ' active' : ''}`} onClick={() => setViewport('mobile')} title="Mobile">📱</button>
          </div>
          <button
            className={`btn btn-sm${editMode ? ' btn-accent' : ''}`}
            onClick={() => { setEditMode(!editMode); setSelected(null) }}
          >
            {editMode ? '✓ Editing' : '✎ Edit'}
          </button>
          {isDirty && (
            <button className="btn btn-sm btn-accent" onClick={() => saveToDb()} disabled={saving}>
              {saving ? '…' : '↑ Save'}
            </button>
          )}
          <div style={{ position: 'relative' }} ref={langMenuRef}>
            <button className="btn btn-sm" onClick={() => setShowLangMenu(p => !p)} disabled={translating}>
              {translating ? `Translating… ${Math.round(translateProgress * 100)}%` : '🌐 Translate'}
            </button>
            {showLangMenu && (
              <div className="lang-menu">
                {LANGUAGES.map(lang => (
                  <button key={lang.code} className="lang-menu-item" onClick={() => translate(lang.code, lang.label)}>
                    {lang.label}
                  </button>
                ))}
              </div>
            )}
          </div>
          <div className="download-group">
            <button className="btn btn-sm" onClick={downloadHtml}>↓ HTML</button>
          </div>
          <div style={{ position: 'relative' }} ref={shopifyDropdownRef}>
            <button
              className={`btn btn-sm${shopifyConn ? ' shopify-connected-btn' : ''}`}
              onClick={() => { setShopifyModal(v => !v); setShopifyStep('credentials'); setShopifyError('') }}
              title={shopifyConn ? `Connected: ${shopifyConn.storeUrl}` : 'Connect Shopify store'}
            >
              {shopifyConn ? `↑ ${shopifyConn.themeName ?? 'Shopify'}` : '↑ Connect Shopify'}
            </button>

            {shopifyModal && (
              <div className="shopify-dropdown" onClick={e => e.stopPropagation()}>
                <div className="shopify-modal-header">
                  <div>
                    <div className="shopify-modal-title">
                      {shopifyStep === 'credentials' ? '↑ Connect Shopify' : '↑ Select Theme'}
                    </div>
                    {shopifyConn && shopifyStep === 'credentials' && (
                      <div className="shopify-modal-connected">Connected: {shopifyConn.storeUrl}</div>
                    )}
                  </div>
                  <button className="modal-close" onClick={() => { setShopifyModal(false); setShopifyStep('credentials'); setShopifyError('') }}>✕</button>
                </div>

                {shopifyStep === 'credentials' ? (
                  <div className="shopify-modal-body">
                    <div className="shopify-field">
                      <label>Store URL</label>
                      <input
                        type="text"
                        placeholder="my-store.myshopify.com"
                        value={shopifyForm.storeUrl}
                        onChange={e => setShopifyForm(f => ({ ...f, storeUrl: e.target.value }))}
                        autoComplete="off"
                      />
                    </div>
                    <div className="shopify-field">
                      <label>Admin API Access Token</label>
                      <input
                        type="password"
                        placeholder="shpat_xxxxxxxxxxxxxxxx"
                        value={shopifyForm.token}
                        onChange={e => setShopifyForm(f => ({ ...f, token: e.target.value }))}
                        autoComplete="off"
                      />
                      <span className="shopify-field-hint">
                        Shopify Admin → Settings → Apps → Develop apps → Create app → Admin API scopes → enable <code>write_themes</code> → Install → copy token
                      </span>
                    </div>
                    {shopifyError && <div className="shopify-error">{shopifyError}</div>}
                    <div className="shopify-modal-actions">
                      {shopifyConn && (
                        <button className="btn btn-sm" style={{ color: 'var(--red)' }} onClick={async () => {
                          await fetch('/api/shopify/connection', { method: 'DELETE' })
                          setShopifyConn(null)
                          setShopifyModal(false)
                        }}>Disconnect</button>
                      )}
                      <button
                        className="btn btn-accent"
                        style={{ marginLeft: 'auto' }}
                        disabled={!shopifyForm.storeUrl || !shopifyForm.token || shopifyConnecting}
                        onClick={connectShopify}
                      >
                        {shopifyConnecting ? <><span className="spinner" style={{ width: 14, height: 14 }} /> Connecting…</> : 'Connect →'}
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="shopify-modal-body">
                    <p style={{ fontSize: 13, color: 'var(--text2)', marginBottom: 4 }}>Choose which theme to push sections to:</p>
                    <div className="shopify-theme-list">
                      {shopifyThemes.map(t => (
                        <label key={t.id} className={`shopify-theme-item${shopifySelectedTheme === t.id ? ' selected' : ''}`}>
                          <input type="radio" name="theme" value={t.id} checked={shopifySelectedTheme === t.id} onChange={() => setShopifySelectedTheme(t.id)} />
                          <span className="shopify-theme-name">{t.name}</span>
                          {t.role === 'main' && <span className="shopify-theme-live">Live</span>}
                        </label>
                      ))}
                    </div>
                    <div className="shopify-modal-actions">
                      <button className="btn btn-sm" onClick={() => setShopifyStep('credentials')}>← Back</button>
                      <button className="btn btn-accent" style={{ marginLeft: 'auto' }} disabled={!shopifySelectedTheme} onClick={saveShopifyTheme}>
                        Save & Finish
                      </button>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ── Builder layout ── */}
      <div className="builder-layout">

        {/* Left nav */}
        <div className="builder-nav">
          <div className="builder-nav-header">
            Sections
            {sections.length > 0 && <span className="builder-nav-count">{sections.length}</span>}
          </div>
          {sections.length === 0 && (
            <div className="builder-nav-empty">Scanning…</div>
          )}
          {sections.map((s, i) => (
            <button
              key={s.id}
              className={`builder-nav-item${selectedSectionId === s.id ? ' active' : ''}`}
              onClick={() => {
                setSelectedSectionId(s.id)
                document.getElementById(`sec-card-${s.id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
              }}
            >
              <span className="builder-nav-num">{i + 1}</span>
              <span className="builder-nav-label">{s.label}</span>
            </button>
          ))}
        </div>

        {/* Canvas */}
        <div className="builder-canvas">
          {sections.length === 0 && (
            <div className="builder-canvas-empty">
              <span className="spinner" />
              Analysing page structure…
            </div>
          )}
          {sections.map(s => (
            <SectionCard
              key={s.id}
              section={s}
              pageStyles={pageStyles}
              viewport={viewport}
              selected={selectedSectionId === s.id}
              aiGenerating={aiGenerating}
              aiTargetId={selectedSectionId}
              copyFeedback={copyFeedback}
              onCleanHtml={generateCleanHtml}
              onCopyRaw={sid => requestSectionHtml(sid, 'copy')}
              onDownload={sid => requestSectionHtml(sid, 'download')}
              onDelete={setDeleteSection}
              onSelect={s => {
                setSelectedSectionId(s.id)
                setSectionCodeLabel(s.label)
                setSectionCodeHtml('loading')
                setSectionCodeIsClean(false)
                setSectionCodeCleanId(null)
                const resolve = (outerHtml: string) => setSectionCodeHtml(outerHtml)
                viewResolve.current = resolve
                iframeRef.current?.contentWindow?.postMessage({ type: 'GET_SECTION_VIEW', id: s.id }, '*')
                setTimeout(() => { if (viewResolve.current === resolve) { viewResolve.current = null; setSectionCodeHtml('') } }, 5000)
              }}
            />
          ))}
        </div>

        {/* Right panel */}
        {sectionCodeHtml && (
          <div className="builder-panel">
            <div className="builder-panel-toolbar">
              <span className="builder-panel-label">
                {sectionCodeIsClean && <span className="builder-panel-badge">✦ Liquid</span>}
                {sectionCodeLabel}
              </span>
              <div style={{ display: 'flex', gap: 6, flexShrink: 0 }}>
                {sectionCodeIsClean && sectionCodeHtml !== 'loading' && (
                  <>
                    <button className="btn btn-sm btn-accent" style={{ fontSize: 10, padding: '3px 8px' }} onClick={applyAiToPage}>Apply</button>
                    <button
                      className="btn btn-sm shopify-push-btn"
                      style={{ fontSize: 10, padding: '3px 8px' }}
                      disabled={shopifyPushing}
                      onClick={pushToShopify}
                      title={shopifyConn ? `Push to ${shopifyConn.themeName}` : 'Connect Shopify first'}
                    >
                      {shopifyPushing ? '…' : shopifyConn ? '↑ Shopify' : '↑ Connect'}
                    </button>
                  </>
                )}
                {sectionCodeHtml !== 'loading' && (
                  <>
                    <button className="btn btn-sm" style={{ fontSize: 11, padding: '3px 8px' }} onClick={() => {
                      navigator.clipboard.writeText(sectionCodeHtml).catch(() => {})
                      setCodeCopied(true)
                      setTimeout(() => setCodeCopied(false), 1500)
                    }}>{codeCopied ? '✓' : '⎘'}</button>
                    <button className="btn btn-sm" style={{ fontSize: 11, padding: '3px 8px' }} onClick={() => {
                      const blob = new Blob([sectionCodeHtml], { type: 'text/plain' })
                      const a = document.createElement('a')
                      a.href = URL.createObjectURL(blob)
                      a.download = `${sectionCodeLabel.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40)}.liquid`
                      a.click()
                    }}>↓</button>
                  </>
                )}
                <button className="builder-panel-close" onClick={() => { setSectionCodeHtml(''); setSelectedSectionId(null); setShopifyPushResult(null) }}>✕</button>
              </div>
            </div>

            {/* Push result */}
            {shopifyPushResult && (
              <div className={`shopify-push-result${shopifyPushResult.ok ? ' ok' : ' err'}`}>
                {shopifyPushResult.ok ? (
                  <>
                    <span>✓ Pushed as <code>{shopifyPushResult.filename}</code></span>
                    <a href={shopifyPushResult.editorUrl} target="_blank" rel="noopener noreferrer">Open Theme Editor ↗</a>
                  </>
                ) : (
                  <span>✕ {shopifyPushResult.error}</span>
                )}
              </div>
            )}

            <div className="builder-panel-body">
              {sectionCodeHtml === 'loading'
                ? <div style={{ padding: 20, color: 'var(--text3)', fontSize: 12, display: 'flex', gap: 8, alignItems: 'center' }}>
                    <span className="spinner" style={{ width: 14, height: 14 }} />
                    {sectionCodeIsClean ? 'Claude is generating Liquid…' : 'Loading…'}
                  </div>
                : <pre>{sectionCodeHtml}</pre>
              }
            </div>

            {/* Element editor (shown when in edit mode and element selected) */}
            {editMode && selected && (
              <div className="builder-element-editor">
                <div className="builder-element-tag">{selected.tag}</div>
                {selected.tag === 'IMG' ? (
                  <>
                    <div className="clone-edit-field"><label className="field-label">Image URL</label><input type="text" value={editSrc} onChange={e => setEditSrc(e.target.value)} placeholder="https://…" /></div>
                    <div className="clone-edit-field"><label className="field-label">Alt text</label><input type="text" value={editText} onChange={e => setEditText(e.target.value)} /></div>
                  </>
                ) : (
                  <div className="clone-edit-field">
                    <label className="field-label">HTML content</label>
                    <textarea value={editText} onChange={e => setEditText(e.target.value)} rows={6} style={{ fontFamily: 'DM Mono, monospace', fontSize: 11, lineHeight: 1.6 }} />
                  </div>
                )}
                <button className="btn btn-accent" onClick={applyEdit} disabled={saving}>{saving ? '…' : 'Apply & Save'}</button>
              </div>
            )}
          </div>
        )}
      </div>

      {/* ── Hidden processing iframe (always present) ── */}
      <iframe
        ref={iframeRef}
        key={`proc-${editMode ? 'edit' : 'view'}`}
        srcDoc={iframeSrc}
        sandbox="allow-scripts allow-same-origin"
        title="page-processor"
        style={{
          position: 'fixed',
          left: editMode ? 0 : -2400,
          top: editMode ? 50 : 0,
          width: editMode ? '100%' : 1280,
          height: editMode ? 'calc(100% - 50px)' : 2,
          opacity: editMode ? 1 : 0,
          pointerEvents: editMode ? 'all' : 'none',
          zIndex: editMode ? 200 : -1,
          border: 'none',
        }}
      />

      {/* ── Edit mode overlay bar ── */}
      {editMode && (
        <div className="edit-mode-bar">
          <span className="edit-mode-indicator">✎ Edit Mode</span>
          <span className="edit-mode-hint">Click any element to edit it</span>
          {selected && (
            <span className="edit-mode-selected">{selected.tag} selected</span>
          )}
          <div style={{ marginLeft: 'auto', display: 'flex', gap: 8 }}>
            {selected && (
              <>
                {selected.tag === 'IMG' ? (
                  <input
                    type="text"
                    value={editSrc}
                    onChange={e => setEditSrc(e.target.value)}
                    placeholder="Image URL"
                    style={{ fontSize: 12, padding: '3px 8px', background: 'var(--bg3)', border: '1px solid var(--border2)', borderRadius: 6, color: 'var(--text)', width: 240 }}
                  />
                ) : (
                  <input
                    type="text"
                    value={editText.replace(/<[^>]*>/g, '')}
                    onChange={e => setEditText(e.target.value)}
                    placeholder="Edit text…"
                    style={{ fontSize: 12, padding: '3px 8px', background: 'var(--bg3)', border: '1px solid var(--border2)', borderRadius: 6, color: 'var(--text)', width: 240 }}
                  />
                )}
                <button className="btn btn-sm btn-accent" onClick={applyEdit} disabled={saving}>{saving ? '…' : 'Apply'}</button>
              </>
            )}
            <button className="btn btn-sm" onClick={() => { setEditMode(false); setSelected(null) }}>✓ Done</button>
          </div>
        </div>
      )}

      <ConfirmModal
        open={!!deleteSection}
        title="Delete this section?"
        message={deleteSection ? `"${deleteSection.label}" will be removed.` : undefined}
        confirmLabel="Delete"
        onConfirm={doDeleteSection}
        onCancel={() => setDeleteSection(null)}
      />

    </>
  )
}
