'use client'

import { useEffect, useRef, useState } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import ConfirmModal from '@/components/ConfirmModal'

interface Clone {
  id: string
  url: string
  title: string
  html: string
  created_at: string
}

interface SelectedElement {
  path: string
  tag: string
  text: string
  html: string
  src?: string | null
  alt?: string | null
}

interface Section {
  id: string   // data-lp-sec attribute value, stable across operations
  tag: string
  label: string
}

interface AiModal {
  sectionLabel: string
  sectionId: string
  loading: boolean
  result: string
  error: string
}

type Viewport = 'desktop' | 'mobile'
type RightTab = 'sections' | 'element'
type PendingAction =
  | { action: 'download' | 'copy'; id: string }
  | { action: 'ai'; id: string; resolve: (html: string) => void }

const LANGUAGES = [
  { code: 'nl', label: 'Dutch' },
  { code: 'en', label: 'English' },
  { code: 'de', label: 'German' },
  { code: 'fr', label: 'French' },
  { code: 'es', label: 'Spanish' },
  { code: 'it', label: 'Italian' },
  { code: 'pt', label: 'Portuguese' },
  { code: 'pl', label: 'Polish' },
  { code: 'ro', label: 'Romanian' },
  { code: 'sv', label: 'Swedish' },
]

function scopeHtmlForShopify(html: string, scopeClass: string): string {
  const styles: string[] = []
  const htmlNoStyles = html.replace(/<style[^>]*>([\s\S]*?)<\/style>/gi, (_, css) => {
    styles.push(css); return ''
  })
  const scopedCss = styles.map(css =>
    css.replace(/([^{}]+)\{/g, (match, selectors) => {
      const scoped = selectors.split(',').map((s: string) => {
        const t = s.trim()
        if (!t || t.startsWith('@') || t.startsWith('from') || t.startsWith('to') || /^\d/.test(t)) return t
        return t.replace(/\bhtml\b/, `.${scopeClass}`).replace(/\bbody\b/, `.${scopeClass}`).replace(/^([^.#:\[])/, `.${scopeClass} $1`)
      }).join(', ')
      return `${scoped} {`
    })
  ).join('\n')
  const bodyMatch = htmlNoStyles.match(/<body[^>]*>([\s\S]*?)<\/body>/i)
  return `{% comment %} Generated by Creative Hub {% endcomment %}\n<div class="${scopeClass}">\n  <style>\n${scopedCss}\n  </style>\n  ${bodyMatch ? bodyMatch[1] : htmlNoStyles}\n</div>\n`
}

export default function CloneEditor() {
  const { id } = useParams<{ id: string }>()
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const [clone, setClone] = useState<Clone | null>(null)
  const [loading, setLoading] = useState(true)
  const [selected, setSelected] = useState<SelectedElement | null>(null)
  const [editText, setEditText] = useState('')
  const [editSrc, setEditSrc] = useState('')
  const [html, setHtml] = useState('')
  const [iframeHtml, setIframeHtml] = useState('')
  const [editMode, setEditMode] = useState(false)
  const [viewport, setViewport] = useState<Viewport>('desktop')
  const [translating, setTranslating] = useState(false)
  const [translateProgress, setTranslateProgress] = useState(0)
  const [showLangMenu, setShowLangMenu] = useState(false)
  const [sections, setSections] = useState<Section[]>([])
  const [activeSectionId, setActiveSectionId] = useState<string | null>(null)
  const [sectionCodeHtml, setSectionCodeHtml] = useState<string>('')
  const [sectionCodeLabel, setSectionCodeLabel] = useState('')
  const [codeCopied, setCodeCopied] = useState(false)
  const [rightTab, setRightTab] = useState<RightTab>('sections')
  const [isDirty, setIsDirty] = useState(false)
  const [saving, setSaving] = useState(false)
  const [deleteSection, setDeleteSection] = useState<Section | null>(null)
  const [aiModal, setAiModal] = useState<AiModal | null>(null)
  const [aiCopied, setAiCopied] = useState(false)
  const [copyFeedback, setCopyFeedback] = useState<string | null>(null)

  const langMenuRef = useRef<HTMLDivElement>(null)
  const htmlRef = useRef(html)
  const sectionsRef = useRef(sections)
  const pendingAction = useRef<PendingAction | null>(null)
  const fullHtmlResolve = useRef<((h: string) => void) | null>(null)
  const savedHtmlRef = useRef('')
  const viewResolve = useRef<((h: string) => void) | null>(null)

  useEffect(() => { htmlRef.current = html }, [html])
  useEffect(() => { sectionsRef.current = sections }, [sections])

  useEffect(() => {
    fetch(`/api/cloned-pages/${id}`)
      .then(r => r.json())
      .then(data => {
        setClone(data)
        setHtml(data.html)
        setIframeHtml(data.html)
        savedHtmlRef.current = data.html
        setLoading(false)
      })
  }, [id])

  useEffect(() => {
    function handleMessage(e: MessageEvent) {
      if (e.data?.type === 'SECTIONS_LOADED') {
        setSections(e.data.sections)
        setActiveSectionId(null)
        setSectionCodeHtml('')
      } else if (e.data?.type === 'ELEMENT_SELECTED') {
        setSelected(e.data)
        setEditText(e.data.tag === 'IMG' ? (e.data.alt ?? '') : (e.data.text ?? ''))
        setEditSrc(e.data.src ?? '')
        setRightTab('element')
      } else if (e.data?.type === 'EDIT_APPLIED') {
        setIsDirty(true)
      } else if (e.data?.type === 'FULL_HTML') {
        if (fullHtmlResolve.current) { fullHtmlResolve.current(e.data.html); fullHtmlResolve.current = null }
      } else if (e.data?.type === 'SECTION_VIEW') {
        if (viewResolve.current) { viewResolve.current(e.data.outerHtml); viewResolve.current = null }
      } else if (e.data?.type === 'SECTION_HTML') {
        const pa = pendingAction.current
        if (!pa || pa.id !== e.data.id) return
        pendingAction.current = null
        if (pa.action === 'ai') {
          pa.resolve(e.data.outerHtml)
        } else if (pa.action === 'copy') {
          navigator.clipboard.writeText(e.data.outerHtml).catch(() => {})
          setCopyFeedback(e.data.id)
          setTimeout(() => setCopyFeedback(null), 1500)
        } else {
          const styleMatches = htmlRef.current.match(/<style[^>]*>[\s\S]*?<\/style>/gi) ?? []
          const fullDoc = `<!DOCTYPE html>\n<html>\n<head>\n<meta charset="utf-8">\n${styleMatches.join('\n')}\n</head>\n<body>\n${e.data.outerHtml}\n</body>\n</html>`
          const section = sectionsRef.current.find(s => s.id === e.data.id)
          const blob = new Blob([fullDoc], { type: 'text/html' })
          const a = document.createElement('a')
          a.href = URL.createObjectURL(blob)
          a.download = `${(section?.label || e.data.id).toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40)}.html`
          a.click()
        }
      }
    }
    window.addEventListener('message', handleMessage)
    return () => window.removeEventListener('message', handleMessage)
  }, [])

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (langMenuRef.current && !langMenuRef.current.contains(e.target as Node)) setShowLangMenu(false)
    }
    document.addEventListener('mousedown', handleClick)
    return () => document.removeEventListener('mousedown', handleClick)
  }, [])

  function injectScript(rawHtml: string, editModeOn: boolean): string {
    const script = `
<script data-lp-injected="1">
(function() {
  var selectedEl = null;
  var activeSec = null;
  var secCounter = 0;

  var SKIP_TAGS = ['STYLE','SCRIPT','LINK','META','NOSCRIPT','HEAD'];

  function getSectionLabel(el) {
    var ariaLabel = el.getAttribute('aria-label');
    if (ariaLabel && ariaLabel.trim().length > 1) return ariaLabel.trim().slice(0, 70);

    var elId = el.id;
    if (elId && elId.length > 2 && elId.length < 50 && !/^\\d+$/.test(elId)) {
      return elId.replace(/[-_]/g, ' ').trim();
    }

    var h = el.querySelector('h1,h2,h3,h4,h5,h6');
    if (h) { var ht = h.textContent.trim(); if (ht.length > 1) return ht.slice(0, 70); }

    var strong = el.querySelector('strong, b');
    if (strong) { var st = strong.textContent.trim(); if (st.length > 2 && st.length < 80) return st.slice(0, 70); }

    var btn = el.querySelector('button, [class*="btn-"], [class*="-btn"], [class*="cta"]');
    if (btn) { var bt = btn.textContent.trim(); if (bt.length > 1 && bt.length < 50) return bt.slice(0, 50); }

    var p = el.querySelector('p');
    if (p) { var pt = p.textContent.trim(); if (pt.length > 3) return pt.slice(0, 70); }

    var text = el.textContent.trim();
    if (text.length > 1) return text.slice(0, 70);

    return el.tagName.toLowerCase();
  }

  function findSectionElements() {
    var candidates = [];

    // Prefer children of <main> or [role=main]
    var mainEl = document.querySelector('main, [role="main"]');
    if (mainEl) {
      candidates = Array.from(mainEl.children).filter(function(el) {
        return SKIP_TAGS.indexOf(el.tagName) === -1 && (el.textContent || '').trim().length > 20;
      });
      // If main has very few direct children, drill one level deeper into the biggest one
      if (candidates.length <= 2 && candidates.length > 0) {
        var expanded = [];
        candidates.forEach(function(el) {
          var sub = Array.from(el.children).filter(function(c) {
            return SKIP_TAGS.indexOf(c.tagName) === -1 && (c.textContent || '').trim().length > 20;
          });
          if (sub.length >= 2) { sub.forEach(function(s) { expanded.push(s); }); }
          else { expanded.push(el); }
        });
        if (expanded.length > candidates.length) candidates = expanded;
      }
    }

    // Fallback: direct body children
    if (candidates.length < 2) {
      candidates = Array.from(document.body.children).filter(function(el) {
        return SKIP_TAGS.indexOf(el.tagName) === -1 && (el.textContent || '').trim().length > 20;
      });
    }

    return candidates;
  }

  function scanSections() {
    var elements = findSectionElements();
    var sections = [];
    elements.forEach(function(el) {
      var secId = el.getAttribute('data-lp-sec');
      if (!secId) { secId = 'sec-' + (++secCounter); el.setAttribute('data-lp-sec', secId); }
      sections.push({ id: secId, tag: el.tagName.toLowerCase(), label: getSectionLabel(el) });
    });
    window.parent.postMessage({ type: 'SECTIONS_LOADED', sections: sections }, '*');
  }

  function getSecEl(id) { return document.querySelector('[data-lp-sec="' + id + '"]'); }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', scanSections);
  } else {
    scanSections();
  }

  window.addEventListener('message', function(e) {
    if (!e.data) return;

    if (e.data.type === 'HIGHLIGHT_SECTION') {
      if (activeSec) { activeSec.style.outline = ''; activeSec.style.outlineOffset = ''; }
      activeSec = getSecEl(e.data.id);
      if (activeSec) {
        activeSec.style.outline = '2px solid #e8c547';
        activeSec.style.outlineOffset = '4px';
        if (e.data.scroll) activeSec.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
      }
    }

    if (e.data.type === 'CLEAR_SECTION') {
      if (activeSec) { activeSec.style.outline = ''; activeSec.style.outlineOffset = ''; activeSec = null; }
    }

    if (e.data.type === 'DELETE_SECTION') {
      var el = getSecEl(e.data.id);
      if (el) {
        el.remove();
        scanSections();
        window.parent.postMessage({ type: 'EDIT_APPLIED' }, '*');
      }
    }

    if (e.data.type === 'REPLACE_SECTION') {
      var el = getSecEl(e.data.id);
      if (el && e.data.html) {
        el.outerHTML = e.data.html;
        scanSections();
        window.parent.postMessage({ type: 'EDIT_APPLIED' }, '*');
      }
    }

    if (e.data.type === 'GET_SECTION_HTML') {
      var el = getSecEl(e.data.id);
      if (el) window.parent.postMessage({ type: 'SECTION_HTML', id: e.data.id, outerHtml: el.outerHTML }, '*');
    }

    if (e.data.type === 'GET_SECTION_VIEW') {
      var el = getSecEl(e.data.id);
      if (el) window.parent.postMessage({ type: 'SECTION_VIEW', id: e.data.id, outerHtml: el.outerHTML }, '*');
    }

    if (e.data.type === 'GET_FULL_HTML') {
      var clone = document.documentElement.cloneNode(true);
      Array.from(clone.querySelectorAll('[data-lp-sec]')).forEach(function(el) { el.removeAttribute('data-lp-sec'); });
      Array.from(clone.querySelectorAll('script[data-lp-injected]')).forEach(function(s) { s.remove(); });
      window.parent.postMessage({ type: 'FULL_HTML', html: '<!DOCTYPE html>' + clone.outerHTML }, '*');
    }

    if (e.data.type === 'UPDATE_ELEMENT' && selectedEl) {
      selectedEl.innerHTML = e.data.html;
      window.parent.postMessage({ type: 'EDIT_APPLIED' }, '*');
    }

    if (e.data.type === 'UPDATE_IMAGE' && selectedEl) {
      if (e.data.src) selectedEl.src = e.data.src;
      if (typeof e.data.alt === 'string') selectedEl.alt = e.data.alt;
      window.parent.postMessage({ type: 'EDIT_APPLIED' }, '*');
    }
  });

  ${editModeOn ? `
  document.addEventListener('click', function(e) {
    e.preventDefault();
    e.stopPropagation();
    if (selectedEl) selectedEl.style.outline = '';
    selectedEl = e.target;
    selectedEl.style.outline = '2px solid #e8c547';
    selectedEl.style.outlineOffset = '2px';
    var path = [];
    var el = selectedEl;
    while (el && el !== document.body) {
      var idx = Array.from(el.parentNode ? el.parentNode.children : []).indexOf(el);
      path.unshift(el.tagName.toLowerCase() + ':nth-child(' + (idx + 1) + ')');
      el = el.parentElement;
    }
    var isImg = selectedEl.tagName === 'IMG';
    window.parent.postMessage({
      type: 'ELEMENT_SELECTED',
      tag: selectedEl.tagName,
      text: selectedEl.innerHTML || '',
      html: selectedEl.innerHTML || '',
      path: path.join(' > '),
      src: isImg ? selectedEl.src : null,
      alt: isImg ? (selectedEl.alt || '') : null,
    }, '*');
  }, true);
  ` : ''}
})();
<\/script>`

    if (rawHtml.includes('</body>')) return rawHtml.replace('</body>', script + '</body>')
    return rawHtml + script
  }

  async function selectSection(section: Section) {
    setActiveSectionId(section.id)
    setSectionCodeLabel(section.label)
    setSectionCodeHtml('loading')
    iframeRef.current?.contentWindow?.postMessage({ type: 'HIGHLIGHT_SECTION', id: section.id, scroll: true }, '*')
    const html = await new Promise<string>(resolve => {
      viewResolve.current = resolve
      iframeRef.current?.contentWindow?.postMessage({ type: 'GET_SECTION_VIEW', id: section.id }, '*')
      setTimeout(() => { viewResolve.current = null; resolve('') }, 5000)
    })
    setSectionCodeHtml(html)
  }

  function clearSection() {
    setActiveSectionId(null)
    setSectionCodeHtml('')
    iframeRef.current?.contentWindow?.postMessage({ type: 'CLEAR_SECTION' }, '*')
  }

  function doDeleteSection() {
    if (!deleteSection) return
    iframeRef.current?.contentWindow?.postMessage({ type: 'DELETE_SECTION', id: deleteSection.id }, '*')
    setDeleteSection(null)
    setActiveSectionId(null)
    setSectionCodeHtml('')
  }

  function requestSectionHtml(id: string, action: 'download' | 'copy') {
    pendingAction.current = { action, id }
    iframeRef.current?.contentWindow?.postMessage({ type: 'GET_SECTION_HTML', id }, '*')
  }

  async function generateCleanHtml(section: Section) {
    setAiModal({ sectionLabel: section.label, sectionId: section.id, loading: true, result: '', error: '' })
    const sectionHtml = await new Promise<string>(resolve => {
      pendingAction.current = { action: 'ai', id: section.id, resolve }
      iframeRef.current?.contentWindow?.postMessage({ type: 'GET_SECTION_HTML', id: section.id }, '*')
      setTimeout(() => { if (pendingAction.current?.action === 'ai') { pendingAction.current = null; resolve('') } }, 5000)
    })
    const currentHtml = savedHtmlRef.current || htmlRef.current
    const pageStyles = (currentHtml.match(/<style[^>]*>([\s\S]*?)<\/style>/gi) ?? []).map(s => s.replace(/<\/?style[^>]*>/gi, '')).join('\n')
    try {
      const res = await fetch('/api/clean-section', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ sectionHtml, pageStyles, pageUrl: clone?.url }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Generation failed')
      setAiModal(prev => prev ? { ...prev, loading: false, result: data.html } : null)
    } catch (err: any) {
      setAiModal(prev => prev ? { ...prev, loading: false, error: err.message } : null)
    }
  }

  function applyAiToPage() {
    if (!aiModal?.result) return
    iframeRef.current?.contentWindow?.postMessage({ type: 'REPLACE_SECTION', id: aiModal.sectionId, html: aiModal.result }, '*')
    setAiModal(null)
  }

  async function applyEdit() {
    if (!selected || !iframeRef.current?.contentWindow) return
    if (selected.tag === 'IMG') {
      iframeRef.current.contentWindow.postMessage({ type: 'UPDATE_IMAGE', src: editSrc, alt: editText }, '*')
      setSelected(prev => prev ? { ...prev, src: editSrc, alt: editText } : null)
    } else {
      iframeRef.current.contentWindow.postMessage({ type: 'UPDATE_ELEMENT', html: editText }, '*')
      setSelected(prev => prev ? { ...prev, text: editText, html: editText } : null)
    }
    await new Promise(r => setTimeout(r, 80))
    await saveToDb(true)
  }

  async function saveToDb(auto = false) {
    if (!auto) setSaving(true)
    const liveHtml = await new Promise<string>(resolve => {
      fullHtmlResolve.current = resolve
      iframeRef.current?.contentWindow?.postMessage({ type: 'GET_FULL_HTML' }, '*')
      setTimeout(() => resolve(htmlRef.current), 4000)
    })
    try {
      await fetch(`/api/cloned-pages/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ html: liveHtml }),
      })
      savedHtmlRef.current = liveHtml
      setIsDirty(false)
    } catch {
      if (!auto) alert('Save failed. Please try again.')
    } finally {
      if (!auto) setSaving(false)
    }
  }

  async function downloadHtml() {
    const content = savedHtmlRef.current || htmlRef.current
    if (!content) return
    const blob = new Blob([content], { type: 'text/html' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${clone?.title || 'clone'}.html`
    a.click()
  }

  function downloadShopify() {
    const content = savedHtmlRef.current || html
    if (!content) return
    const scopeClass = `lp-clone-${id.slice(0, 8)}`
    const liquid = scopeHtmlForShopify(content, scopeClass)
    const blob = new Blob([liquid], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${(clone?.title || 'clone').toLowerCase().replace(/\s+/g, '-')}.liquid`
    a.click()
  }

  async function translate(langCode: string, langLabel: string) {
    setShowLangMenu(false)
    setTranslating(true)
    setTranslateProgress(0)
    setSelected(null)
    try {
      const res = await fetch('/api/translate-page', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id, language: langLabel }),
      })
      if (!res.ok || !res.body) throw new Error((await res.json()).error || 'Translation failed')
      const reader = res.body.getReader()
      const decoder = new TextDecoder()
      let buffer = ''
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        buffer += decoder.decode(value, { stream: true })
        const parts = buffer.split('\n\n')
        buffer = parts.pop() ?? ''
        for (const part of parts) {
          if (!part.startsWith('data: ')) continue
          const event = JSON.parse(part.slice(6))
          if (event.type === 'progress') setTranslateProgress(event.value)
          else if (event.type === 'done') {
            setTranslateProgress(1)
            setHtml(event.html); setIframeHtml(event.html); savedHtmlRef.current = event.html; setIsDirty(false)
          }
          else if (event.type === 'error') throw new Error(event.error)
        }
      }
    } catch (err: any) {
      alert(err.message)
    } finally {
      setTimeout(() => { setTranslating(false); setTranslateProgress(0) }, 600)
    }
  }

  if (loading) return (
    <>
      <div className="topbar"><div className="topbar-title">Loading…</div></div>
      <div className="content" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 300 }}>
        <span className="spinner" />
      </div>
    </>
  )

  if (!clone) return (
    <>
      <div className="topbar"><div className="topbar-title">Not found</div></div>
      <div className="content"><Link href="/landing-page" className="btn">← Back</Link></div>
    </>
  )

  const iframeSrc = injectScript(iframeHtml || html, editMode)

  return (
    <>
      <div className="topbar" style={{ position: 'relative' }}>
        {translating && <div className="translate-progress-bar" style={{ width: `${Math.round(translateProgress * 100)}%` }} />}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <Link href="/landing-page" className="btn btn-sm">← Back</Link>
          <div className="topbar-title" style={{ fontSize: 15 }}>{clone.title || 'Untitled Page'}</div>
          {isDirty && <span className="unsaved-dot" title="Unsaved changes" />}
        </div>
        <div className="topbar-actions">
          <div className="viewport-toggle">
            <button className={`viewport-btn${viewport === 'desktop' ? ' active' : ''}`} onClick={() => { setIframeHtml(savedHtmlRef.current || html); setViewport('desktop') }} title="Desktop">🖥</button>
            <button className={`viewport-btn${viewport === 'mobile' ? ' active' : ''}`} onClick={() => { setIframeHtml(savedHtmlRef.current || html); setViewport('mobile') }} title="Mobile">📱</button>
          </div>
          <button className={`btn btn-sm${editMode ? ' btn-accent' : ''}`} onClick={() => { setIframeHtml(savedHtmlRef.current || html); setEditMode(!editMode); setSelected(null) }}>
            {editMode ? '✓ Editing' : '✎ Edit'}
          </button>
          {isDirty && <button className="btn btn-sm btn-accent" onClick={() => saveToDb()} disabled={saving}>{saving ? '…' : '↑ Save'}</button>}
          <div style={{ position: 'relative' }} ref={langMenuRef}>
            <button className="btn btn-sm" onClick={() => setShowLangMenu(p => !p)} disabled={translating}>
              {translating ? `Translating… ${Math.round(translateProgress * 100)}%` : '🌐 Translate'}
            </button>
            {showLangMenu && (
              <div className="lang-menu">
                {LANGUAGES.map(lang => <button key={lang.code} className="lang-menu-item" onClick={() => translate(lang.code, lang.label)}>{lang.label}</button>)}
              </div>
            )}
          </div>
          <div className="download-group">
            <button className="btn btn-sm" onClick={downloadHtml}>↓ HTML</button>
            <button className="btn btn-sm btn-accent" onClick={downloadShopify}>↓ Shopify</button>
          </div>
        </div>
      </div>

      <div className="clone-editor">
        <div className="clone-preview-pane">
          <div className="clone-preview-toolbar">
            <div className="clone-preview-url">{clone.url}</div>
            <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexShrink: 0 }}>
              {viewport === 'mobile' && <span style={{ fontSize: 11, color: 'var(--text3)', fontFamily: 'DM Mono' }}>390px</span>}
              {editMode && <span style={{ fontSize: 11, color: 'var(--accent)', fontFamily: 'DM Mono' }}>click to edit</span>}
            </div>
          </div>
          <div className="clone-iframe-wrap" style={{ background: viewport === 'mobile' ? 'var(--bg)' : undefined }}>
            <div className={`clone-iframe-inner${viewport === 'mobile' ? ' mobile' : ''}`}>
              <iframe ref={iframeRef} key={`${editMode ? 'edit' : 'view'}-${viewport}`} srcDoc={iframeSrc} sandbox="allow-scripts allow-same-origin" title="Page preview" />
            </div>
          </div>
        </div>

        <div className="clone-edit-pane">
          <div className="clone-edit-tabs">
            <button className={`clone-edit-tab${rightTab === 'sections' ? ' active' : ''}`} onClick={() => setRightTab('sections')}>
              Sections {sections.length > 0 && <span className="clone-tab-count">{sections.length}</span>}
            </button>
            <button className={`clone-edit-tab${rightTab === 'element' ? ' active' : ''}`} onClick={() => setRightTab('element')}>
              Element
            </button>
          </div>

          {rightTab === 'sections' ? (
            <div className="clone-sections-split">
              <div className="clone-sections-list">
                {sections.length === 0 ? (
                  <div className="clone-edit-empty">
                    <span style={{ fontSize: 28, opacity: 0.2 }}>◫</span>
                    Scanning sections…
                  </div>
                ) : (
                  <>
                    {activeSectionId && <button className="clone-section-clear" onClick={clearSection}>✕ Clear highlight</button>}
                    {sections.map(s => (
                      <div
                        key={s.id}
                        className={`clone-section-item${activeSectionId === s.id ? ' active' : ''}`}
                        onClick={() => selectSection(s)}
                      >
                        <span className="clone-section-tag">{s.tag}</span>
                        <span className="clone-section-label">{s.label}</span>
                        <div className="clone-section-actions">
                          <button className="btn btn-sm clone-section-ai-btn" title="Generate clean HTML with AI" onClick={e => { e.stopPropagation(); generateCleanHtml(s) }} style={{ padding: '3px 7px', fontSize: 11 }}>✦</button>
                          <button className="btn btn-sm" title="Copy raw HTML" onClick={e => { e.stopPropagation(); requestSectionHtml(s.id, 'copy') }} style={{ padding: '3px 7px', fontSize: 11 }}>{copyFeedback === s.id ? '✓' : '⎘'}</button>
                          <button className="btn btn-sm" title="Download as HTML file" onClick={e => { e.stopPropagation(); requestSectionHtml(s.id, 'download') }} style={{ padding: '3px 7px', fontSize: 11 }}>↓</button>
                          <button className="btn btn-sm" title="Delete section" onClick={e => { e.stopPropagation(); setDeleteSection(s) }} style={{ padding: '3px 7px', fontSize: 11, color: 'var(--red)' }}>✕</button>
                        </div>
                      </div>
                    ))}
                  </>
                )}
              </div>

              {sectionCodeHtml && (
                <div className="clone-section-code-panel">
                  <div className="clone-section-code-toolbar">
                    <span className="clone-section-code-title">{sectionCodeLabel}</span>
                    <button
                      className="btn btn-sm"
                      style={{ fontSize: 11, padding: '3px 8px' }}
                      onClick={() => {
                        navigator.clipboard.writeText(sectionCodeHtml).catch(() => {})
                        setCodeCopied(true)
                        setTimeout(() => setCodeCopied(false), 1500)
                      }}
                    >
                      {codeCopied ? '✓ Copied' : '⎘ Copy'}
                    </button>
                    <button className="btn btn-sm" style={{ fontSize: 11, padding: '3px 8px' }} onClick={() => { if (activeSectionId) requestSectionHtml(activeSectionId, 'download') }}>↓</button>
                    <button className="clone-section-code-close" onClick={() => { setSectionCodeHtml(''); setActiveSectionId(null); clearSection() }}>✕</button>
                  </div>
                  <div className="clone-section-code-body">
                    {sectionCodeHtml === 'loading'
                      ? <div style={{ padding: '16px', color: 'var(--text3)', fontSize: 12 }}>Loading…</div>
                      : <pre>{sectionCodeHtml}</pre>
                    }
                  </div>
                </div>
              )}
            </div>
          ) : (
            <>
              <div className="clone-edit-header">
                <div className="clone-edit-hint">{editMode ? 'Click any element in the preview to edit it.' : 'Enable Edit Mode to select and modify elements.'}</div>
              </div>
              {!editMode ? (
                <div className="clone-edit-empty"><span style={{ fontSize: 32, opacity: 0.2 }}>✎</span>Enable Edit Mode to<br />interact with the page.</div>
              ) : !selected ? (
                <div className="clone-edit-empty"><span style={{ fontSize: 32, opacity: 0.2 }}>◎</span>Click any element<br />in the preview to edit it.</div>
              ) : (
                <div className="clone-edit-selection">
                  <div><span className="clone-edit-tag">{selected.tag}</span></div>
                  {selected.tag === 'IMG' ? (
                    <>
                      <div className="clone-edit-field"><label className="field-label">Image URL</label><input type="text" value={editSrc} onChange={e => setEditSrc(e.target.value)} placeholder="https://…" /></div>
                      <div className="clone-edit-field"><label className="field-label">Alt text</label><input type="text" value={editText} onChange={e => setEditText(e.target.value)} /></div>
                    </>
                  ) : (
                    <div className="clone-edit-field">
                      <label className="field-label">HTML content</label>
                      <textarea value={editText} onChange={e => setEditText(e.target.value)} rows={7} style={{ fontFamily: 'DM Mono, monospace', fontSize: 11, lineHeight: 1.6 }} />
                    </div>
                  )}
                  <button className="btn btn-accent" onClick={applyEdit} disabled={saving}>{saving ? '…' : 'Apply & Save'}</button>
                  <div className="notice-box">Applies the change live and saves automatically.</div>
                </div>
              )}
            </>
          )}
        </div>
      </div>

      {aiModal && (
        <div className="modal-backdrop" onClick={() => !aiModal.loading && setAiModal(null)}>
          <div className="ai-section-modal" onClick={e => e.stopPropagation()}>
            <div className="ai-section-modal-header">
              <div>
                <div className="ai-section-modal-title">✦ AI Clean HTML</div>
                <div className="ai-section-modal-sub">{aiModal.sectionLabel}</div>
              </div>
              {!aiModal.loading && <button className="modal-close" onClick={() => setAiModal(null)}>✕</button>}
            </div>
            {aiModal.loading ? (
              <div className="ai-section-loading"><span className="spinner" /><span>Claude is analyzing and rewriting this section…</span></div>
            ) : aiModal.error ? (
              <div className="ai-section-error">{aiModal.error}</div>
            ) : (
              <>
                <div className="ai-section-code"><pre>{aiModal.result}</pre></div>
                <div className="ai-section-actions">
                  <button className="btn btn-sm" onClick={() => { navigator.clipboard.writeText(aiModal.result); setAiCopied(true); setTimeout(() => setAiCopied(false), 1500) }}>{aiCopied ? '✓ Copied' : '⎘ Copy HTML'}</button>
                  <button className="btn btn-sm" onClick={() => { const blob = new Blob([aiModal.result], { type: 'text/html' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `${aiModal.sectionLabel.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40)}-clean.html`; a.click() }}>↓ Download</button>
                  <button className="btn btn-sm btn-accent" onClick={applyAiToPage}>Apply to Page</button>
                </div>
              </>
            )}
          </div>
        </div>
      )}

      <ConfirmModal
        open={!!deleteSection}
        title="Delete this section?"
        message={deleteSection ? `"${deleteSection.label}" will be removed. Hit ↑ Save to persist.` : undefined}
        confirmLabel="Delete"
        onConfirm={doDeleteSection}
        onCancel={() => setDeleteSection(null)}
      />
    </>
  )
}
